Article Menu Item
joomla/test-system pull request #48
Opened 2018-07-27 19:57 UTC by Samgithub1997

You also need MenuItemStep file which is another PR of Menu Item #43 .
Please review and suggest changes @puneet0191  @yvesh

2018-07-28 04:48 UTC, puneet0191 requested changes
Minor changes please

2018-07-28 04:48 UTC, puneet0191 commented on src/_support/Page/Acceptance/Administrator/ContentListPage.php
> +	public static $seeFeatured = "//table[@id='articleList']//*//span[@class='icon-featured']";
use of wildcard in xpath is going to be very costly, try to be absolutely sure about the exact path please.

2018-07-28 04:48 UTC, puneet0191 commented on src/acceptance/administrator/components/com_menu_article/ArticleMenuCest.php
> +	 * Trah Article
Trash*

2018-07-28 04:48 UTC, puneet0191 commented on src/acceptance/administrator/components/com_menu_article/ArticleMenuCest.php
> +		FrontEnd::articleIsNotVisible($I, $this->menuItemName, $this->articleTitle);
you could just inject the step object to this test

2018-07-30 20:48 UTC, Samgithub1997 commented
@puneet0191 @yvesh Please review again. I made the changes

2018-08-07 05:35 UTC, puneet0191 approved these changes

2018-08-07 05:35 UTC, merged